### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by cieraclaire** [cieraclaire/restaurant-website#3]
Hey Thomas, I am not really understanding why my content goes all wacky when I go from mobile view to tablet, etc. I don't have any code in CSS that changes it to a smaller size or different position. Is that my problem? I get extremely overwhelmed when I look at it 👎 

@thomasjbradley

**Comment by cieraclaire** [comment]
Got it! I've been answering my own question haha. Victoria helped and it's all good :)!

@thomasjbradley

**Comment by thomasjbradley** [comment]
Great!
